extends: existence
message: "Use 'ISO-8601 format, not '%s'."
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#dates'
ignorecase: true
level: warning
nonword: true
tokens:
  - '\d{1,2}-\d{1,2}-\d{4}' # 1-23-2018
  - '(?m)^(([0-9])|([0-2][0-9])|([3][0-1])) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4}$' # 12 Jan 2014
  - '(?m)^([0-9]{4})(-?)(1[0-2]|0[1-9])(3[01]|0[1-9]|[12][0-9])$' #20100820
  - '(?m)^((19\d{2})|(20\d{2}))/(((02)-(0[1-9]|[1-2][0-9]))|(((0(1|[3-9]))|(1[0-2]))/(0[1-9]|[1-2][0-9]|30))|((01|03|05|07|08|10|12)-(31)))$' # 2020/01/15