extends: existence
message: "Don't use foo, bar or foobar as data. Use actual data. '%s'"
link: https://docs.google.com/document/d/1kT8423WTLIRHZC-5wQuu3_fuiNqqmDQ7zny7f4VqBPA/edit#heading=h.rwrhph6cjuci
nonword: true
level: error
tokens:
  - (?:(?:(?:foo))|(?:(?:bar))|(?:(?:foobar)))