extends: existence
message: Use numerals when writing about a specific number, regardless of how big it is or where it appears in the sentence. Spell-out numbers when they don’t represent specific facts. '%s'
link: "https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#numbers"
level: warning
ignorecase: true
nonword: true
raw:
    - '(?mi)\b(?:one|two|three|four|five|six|seven|eight|nine|ten|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|million)\b'
    # - ((?:f(?:ive|our)|s(?:even|ix)|t(?:hree|wo)|(?:ni|o)ne|eight))|((?:(?:(?:s(?:even|ix)|f(?:our|if)|nine)te|e(?:ighte|lev))en|t(?:(?:hirte)?en|welve)))|(?:fifty|thirty|twenty|thousand|million)

    
# This only checks for numbers that are spelled out. 
# Numbers that don't represent concrete facts can be kept. Review your writing and edit as needed.
