extends: substitution
message: "Use '%s' instead of '%s'".
link: ''
level: warning
ignorecase: true
swap:
  abort: use end, exit or stop
  afterwards: afterward
  anti-virus: antivirus
  backwards: backward
  checkbox: check box
  checkmark: check mark
  code snipped: code example | code sample
  code snippet: code example | code sample
  doubleclick: double-click
  doubleclicking: double-clicking
  e.g: for example
  eg: for example
  etc.: Do not use. Just write out the list
  etc: Do not use, just write out the list
  ig: in other words
  i.g.: in other words
  unix: Unix
  useage: usage
  via: through
  web site: website
  Website: website
  since: because
  blank: empty
  above: previous | preceding | earlier
  current: active | open
  and/or: Use one or the other
  as well as: in addtion | and | such as
  below: later | following
  unmark: clear | deselect
  child folder: subfolder
  per: for each
  via: through
  i.e.: such as | for example
  user name: username
  user-name: username
  log in: login
  log-in: login
  log into: log in to
  login to: log in to
  log-in to: log in to
  e-mail: email
  e mail: email
  back-up: backup
  back up: backup
  bullet list: bulleted list
  Cancelled: Canceled
  Cancelling: Canceling
  Continual: Continuous
  doubleclick: double-click
  double click: double-click
  web site: website
  drop-down: dropdown
  drop down: dropdown
  plug-in: plugin
  plug in: plugin
  two factor: two-factor
  chat-bot: chatbot
  chat bot: chatbot
  white list: whitelist
  white-list: whitelist
  MS: Metasploit


# This only points out terms that are often used incorrectly. It is a reminder to check that your useage is correct. 




